sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - DOCKER_REPO=oanhnn/alpine-base
    # DOCKER_USER
    - secure: "xn/bcwplaBSxedMT2jrQ3Hy4YnmhShwPrJQmTbfj76zUMy48GYYDnLd6+mvHHZMVssrVUAo9xKpaRtmhyPZrtRmVWFMD682YoL0hTZ0+GiJWHEwAiu8E1zHDimHwrnPntdsmQV5OEa+H7HiDHma7odj7haqIRJgYthqEpLlEaRtrJNl1WKrvBq+pI9SdJVX4QxCfEFsN9LvxAJCGSEmn82wyj4jo6D8xO8ys2CEDFr/TMSXXTOz0Y01xSxmKYIIFHvBijSIRv3qbRnssmq5vgSNMGXV1tPMIdLFW+GOCZi7lYUxJ3V7u/Ai+tiWYkZYGWtDA9FZBiRByv3c6waGHS/Ye4nmRnvi1Z6RwfZJKLLKw+4MeSIUdRt94bo31ZmtWcb8SHVAV5QVhU+rS5vOkDFny37W7ClLrXbq0VwCtPQp/j6Ay5xCbzfFnYLHIV8Effd43zx4MVbPKTR/R+MMT7G24398q7QzC1cW+aPgEf8CpsH4Pd7npIRUqsrILVpoZW+IC4NDbnf7K5Ir6HgM/T68QDAOLxOn3tPa5hPrdwlIbRhJ4bYsCEG+lpIVRlwmhZh+qrAK+m8cKXlognwCpff63OVUeiSLOYzGnXbeV5+mmmL1WHn6OuRQJHNL4jBbkLRqjnKS7f3KzmfkyU2HBif7P/bAsJzYiGAXPm+8gUzE="
    # DOCKER_PASSWORD
    - secure: "MPy7HltVpNCPV+oaMaTNbDkdJofs401royaN0guNongB5MbU8IhmzRxmqtJZBtCgjMlixK+f8aIWYH7VhEnGC+wjaFyIoUJSFBrmiLKfiKQbli6cKPigekv8UJaKQ4xRK2i58trWEWF3IRq6pqv6/GKyIF6fyo6v3ntZhqjva1ZlDLwBofPilmUiJTYJ+QvmaxV4o80pDDo2IcPwT6MrcvVTJMsIrCjqLRmjlTUQAkL234sbrvh61DKlF3phOB+lcZqwep9Y1efTrfqMvE/hZFHOrfx1o76U6wu1LqIOp2VlISTP62tWnlSFzlVGRxN2DZIX/D5Ck1ramAsHEguxkn3oHM5wt2vcmxQ/maTezvxJ2kRmnEvHAfrcTMgkdzOwhdo4N9cS/VJuG/c4PG3SDgS4kWB1NfCUjmGBNlvsivvhpxt34RDtEhvovL7PV/WnZibxoAHKccsEWaVFKoFsaA82a3XSzzIfhPmGlZlCIIktshI3m8L4ngZCPDqdT4IstGR6yrLeTR93woLaIzOB/I8l164CUr4yhjkhGy0idxaEKX4c6o9rQ4faZKtgDdISQ/G/ewaPWkAHHn8F2nUiqeRzn7rablw7q6StZiX+0hob7Ej64rpmvh+yJLx16V+wTMe+c6tlbcw3E0DYxi8cF79gBdxwFPIv1PHW0Hay+Ig="

script:
  - docker build -f Dockerfile -t $DOCKER_REPO:$COMMIT .
  - docker run -d --name testcontainer $DOCKER_REPO:$COMMIT
  # Your test scripts
  - docker ps

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- if [[ ! -z "$TRAVIS_TAG" ]]; then
  docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:$TRAVIS_TAG;
  docker push $DOCKER_REPO:$TRAVIS_TAG;
  fi
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
  docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:latest;
  docker push $DOCKER_REPO:latest;
  fi
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "develop" ]]; then
  docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:develop;
  docker push $DOCKER_REPO:develop;
  fi
